name: Run Security Tests with ZAP and Behave

on:
  workflow_dispatch:

jobs:
  run_security_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install zap-cli behave selenium

      - name: Install ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2.12.0_Linux.tar.gz
          tar -xvzf ZAP_2.12.0_Linux.tar.gz
          sudo mv ZAP_2.12.0 /opt/zap
          export PATH=$PATH:/opt/zap

      - name: Start ZAP Daemon
        run: |
          nohup /opt/zap/zap.sh -daemon -port 8080 -host 0.0.0.0 &

      - name: Wait for ZAP to start
        run: sleep 30 

      - name: Run Behave Security Tests
        run: |
          behave --tags=@security

      - name: Generate ZAP Report
        run: |
          /opt/zap/zap-cli report -o reports/security/zap-report.html -f html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: security-zap-report
          path: reports/security/zap-report.html
