name: Run Accessibility Tests with Axe-Core and Behave

on:
  workflow_dispatch:

jobs:
  run_accessibility_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install behave selenium axe-selenium-python

      - name: Run Behave Accessibility Tests
        run: |
          behave --tags=@accessibility

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-test-reports
          path: reports/accessibility/
